name: Run nanDECK and Upload Export

on:
  push

jobs:
  build-nandeck:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout

    - name: Run nanDECK
      run: |
        .\nandeck\nanDECK.exe .\nandeck\card-deck.txt /exec
      shell: cmd

    - name: Upload Export Folder
      uses: actions/upload-artifact
      with:
        name: nandeck-export
        path: nandeck/export
        retention-days: 1
